#!/bin/sh

# This script is a convenience script to start the Ibis MPJ registry server
# from the MPJ installation, specified in the $MPJ_HOME environment variable.

# Check MPJ_HOME.
if [ -z "$MPJ_HOME" ];  then
    echo "please set MPJ_HOME to the location of your Ibis MPJ_HOME installation" 1>&2
    exit 1
fi

exec "$MPJ_HOME"/scripts/mpj-run -Xmx256M ibis.ipl.server.Server "$@"
