#!/bin/sh

# Utility script to run the Ibis frontend on the specified arguments.

if [ -z "$MPJ_HOME" ];  then
    echo "please set MPJ_HOME to the location of your Ibis MPJ installation" 1>&2
    exit 1
fi

java -classpath "$CLASSPATH:$MPJ_HOME/lib/"'*' ibis.compile.Ibisc "$@"
